import Head from 'next/head';
import Image from 'next/image';
import styles from '@styles/Home.module.css';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const Home = () => {
  /** Handles default route */
  const router = useRouter();

  useEffect(() => {
    router.push({
      pathname: `/calender`,
      query: {
        dateFrom: '2022-10-17',
        dateTo: '2022-12-31',
      },
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Go to Calender Now</h1>
    </div>
  );
};

export default Home;
